export enum GAME_STATUS {
	DRAW = 'draw',
	WIN = 'win',
	PLAYING = 'playing',
}

export enum GAME_VALUES {
	CROSS = 'X',
	CIRCLE = 'O',
	VOID = '',
}

export const DEFAULT_GAME_STATE = [
	GAME_VALUES.VOID,
	GAME_VALUES.VOID,
	GAME_VALUES.VOID,
	GAME_VALUES.VOID,
	GAME_VALUES.VOID,
	GAME_VALUES.VOID,
	GAME_VALUES.VOID,
	GAME_VALUES.VOID,
	GAME_VALUES.VOID,
];
